### PR TITLE
create dynamic global table view and used the table view in diagnosis skill

### PR DESCRIPTION
**Pull request by mithun-grmtech**

### CODE REVIEW

**Review by vikaskedia — CHANGES_REQUESTED** [review]
I need screenshots when changes are made in UI. Look at commits by Sanjay

**Comment by mithun-grmtech** [comment]
Add diagnosis 1
diagnosis add popup

**Comment by mithun-grmtech** [comment]
after save diagnosis

**Comment by mithun-grmtech** [comment]
add new one

**Comment by mithun-grmtech** [comment]
> I need screenshots when changes are made in UI. Look at commits by Sanjay

Sir, I Added the screenshots

**Review by vikaskedia — APPROVED** [review]

**Pull request merged**
